# Spring properties
spring:
  application:
     name: cmplLanding
  logging:
    level:
      root: INFO
      org.springframework.web: ERROR
      org.hibernate: ERROR
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      
# HTTP Server
server:
  port: 3232  # HTTP (Tomcat) port
